### ISSUE TITLE
What' s your OSS development workflow

### ISSUE THREAD

**Issue by monkindey** [egoist/ama#10]
Hi, @egoist 

When I create the OSS project in github, and must sync to the npm, what's your workflow. Can you make it automatic or templated ? Maybe you can write something down about the workflow of the OSS development, I believe we can learn a lot from you.

Thanks !

**Comment by egoist** [comment]
Here's [how](https://medium.com/@sox/my-oss-workflow-part-1-ec9f7c5dccf6#.rdygrdcna) I create a new npm/browser lib, might publish more about OSS in the future.

Basically I use a template + a release script([np](https://github.com/sindresorhus/np) or [kanpai](https://github.com/egoist/kanpai)), I tried [semantic-release](https://github.com/semantic-release/semantic-release) but always failed setting it up.

**Comment by monkindey** [comment]
Thanks a lot, learn a lot from you.
