### ISSUE TITLE
一生推的番有哪些？

### ISSUE THREAD

**Issue by geekplux** [egoist/ama#5]

**Comment by JmPotato** [comment]
命运石之门

**Comment by egoist** [comment]
太多了 😂

- 未来日记
- 死亡笔记
- 叛逆的鲁鲁修
- 命运石之门
- Psycho Pass
- ...

![img_20160220_150408](https://cloud.githubusercontent.com/assets/8784712/13195087/50490d20-d7e3-11e5-9b6d-e4814ae24a3d.jpg)
