### ISSUE TITLE
How do you learn new Concepts

### ISSUE THREAD

**Issue by Crispy-rw** [egoist/ama#5]
You have been in this industry for many years, and I have also seen many of the tools you built. How do you learn new concepts because for example when I hear a new concept like SSR but I can't find enough resources to implement it myself. How do you keep improving your skills?

**Comment by mdbetancourt** [comment]
i'm interested too :thinking:, in my case i just read works of other developers about that

**Comment by Crispy-rw** [comment]
Looks like this Issue won't be answered
