### ISSUE TITLE
What do you think of JavaScript decorators?

### ISSUE THREAD

**Issue by skimhugo** [egoist/ama#7]
https://github.com/tc39/notes/blob/HEAD/meetings/2021-07/july-14.md#decorators-update

and one more question:How do you think ESBuild's support strategy for decorators will change？

**Comment by egoist** [comment]
I haven't been following the decorator proposal so I need a tldr 😅 but I think esbuild's decorator support entirely depends on how typescript will handle the new proposal. they will probably switch to the new spec by default with an option to enable legacy decorators support.

**Comment by skimhugo** [comment]
I found esbuild will never support emitDecoratorMetadata. What do you think about it?
